import { Inter, Quicksand, Lora, Playfair, EB_Garamond } from 'next/font/google'
import './globals.css'
import Footer from './components/Footer'
import Navbar from './components/Navbar'
import Navbar2 from './components/Navbar2'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const quicksand = Quicksand({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-quicksand',
})

const lora = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lora'
})

const playfair = Playfair({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair'
})

const eb_garamond = EB_Garamond({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-eb_garamond'
})


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${quicksand.variable} ${lora.variable} ${playfair.variable} ${eb_garamond.variable}`}>
      <body className='font-eb_garamond'>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
